### ISSUE TITLE
Project compilation errors/warnings

### ISSUE THREAD

**Issue by Arkshine** [kapilratnani/DocIt#2]
Hi, 

Using VS 2010, your project as it is, doesn't compile properly, at least not all.

There is an error with resouce.rc/resource.h files not found for the language dll, I guess just a matter of setting properly path.
The PHP language is not organized properly and it misses some files.
And finally, there is a warning about a conflict with the default 'LIBCMT' library, not sure what to do.

It would be nice to have a clean project.

Thanks.

**Comment by kapilratnani** [comment]
Hi,
   Some files are missing, i am adding them..

Thank you,
